name: CD3 Export

on:
  workflow_dispatch:  # You can also use push, schedule, etc.

jobs:
  export-cd3:
    runs-on: ubuntu-latest  # Or self-hosted if using custom runners

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Optional if your scripts need dependencies

    - name: Run CD3 Export
      run: |
        cd oci_tools/cd3_automation_toolkit/user-scripts
        python setUpOCI.py tenancies/vishal/vishal_setUpOCI.properties

    - name: Upload Terraform Files (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: terraform-files
        path: tenancies/vishal/terraform_files
